#!/usr/bin/env python3
"""Convert every file in a CGM corpus and report what succeeded.

This measures conversion coverage: whether the converter consumes each file in
the corpus and emits well-formed SVG. It is NOT a WebCGM conformance
certification -- that requires comparing rendered output against the reference
images using the official test methodology, which this does not do.

Usage:
    python scripts/corpus-report.py --cli build/bin/opencgm_cli \
        --corpus testdata/webcgm21-ts --out docs/corpus-report.md
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import itertools
import re
import subprocess
import sys
import tempfile
import time
import xml.etree.ElementTree as ET
from pathlib import Path

PROFILES = ["webcgm", "s1000d", "compat"]

# The <desc> element records the profile name, so it differs by construction.
# Strip it before comparing profiles against each other.
DESC = re.compile(rb"<desc>.*?</desc>", re.S)


def find_cgms(corpus: Path) -> list[Path]:
    seen = {}
    for pat in ("**/*.cgm", "**/*.CGM"):
        for p in corpus.glob(pat):
            seen[p.resolve()] = p
    return sorted(seen.values())


def group_of(path: Path, corpus: Path) -> str:
    rel = path.relative_to(corpus)
    return rel.parts[0] if len(rel.parts) > 1 else "(root)"


def convert(cli: Path, profile: str, src: Path, dst: Path, timeout: int):
    started = time.perf_counter()
    try:
        proc = subprocess.run(
            [str(cli), "--profile", profile, str(src), str(dst)],
            capture_output=True, timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return "timeout", 0.0, 0, "exceeded time limit", None
    elapsed = time.perf_counter() - started

    if proc.returncode != 0:
        err = (proc.stderr or b"").decode("utf-8", "replace").strip().splitlines()
        return "error", elapsed, 0, (err[-1] if err else f"exit {proc.returncode}"), None
    if not dst.exists():
        return "no-output", elapsed, 0, "converter reported success but wrote nothing", None

    size = dst.stat().st_size
    digest = hashlib.sha256(DESC.sub(b"", dst.read_bytes())).hexdigest()
    try:
        ET.parse(dst)
    except ET.ParseError as exc:
        return "malformed", elapsed, size, f"SVG did not parse: {exc}", digest
    return "ok", elapsed, size, "", digest


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cli", type=Path, required=True)
    ap.add_argument("--corpus", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--profiles", nargs="*", default=PROFILES)
    ap.add_argument("--timeout", type=int, default=60)
    args = ap.parse_args()

    if not args.cli.exists():
        print(f"error: converter not found: {args.cli}", file=sys.stderr)
        return 2
    files = find_cgms(args.corpus)
    if not files:
        print(f"error: no CGM files under {args.corpus}", file=sys.stderr)
        return 2

    print(f"{len(files)} files x {len(args.profiles)} profiles")
    results = {}
    failures = []
    digests = collections.defaultdict(dict)
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        for profile in args.profiles:
            per_group = collections.defaultdict(collections.Counter)
            total_time = 0.0
            total_bytes = 0
            for i, src in enumerate(files, 1):
                dst = tmpdir / f"{profile}_{i}.svg"
                status, elapsed, size, detail, digest = convert(
                    args.cli, profile, src, dst, args.timeout)
                digests[src.name][profile] = digest
                per_group[group_of(src, args.corpus)][status] += 1
                total_time += elapsed
                total_bytes += size
                if status != "ok":
                    failures.append((profile, src.name, status, detail))
                if dst.exists():
                    dst.unlink()
            results[profile] = (per_group, total_time, total_bytes)
            ok = sum(c["ok"] for c in per_group.values())
            print(f"  {profile}: {ok}/{len(files)} ok, {total_time:.1f}s")

    statuses = ["ok", "error", "malformed", "no-output", "timeout"]
    lines = [
        "# Corpus conversion report",
        "",
        "Generated by `scripts/corpus-report.py`. Reproduce with:",
        "",
        "```bash",
        "python scripts/fetch-testdata.py",
        "python scripts/corpus-report.py --cli build/bin/opencgm_cli \\",
        "    --corpus testdata/webcgm21-ts --out docs/corpus-report.md",
        "```",
        "",
        "**What this measures:** whether the converter consumes each file in the",
        "corpus and emits well-formed, parseable SVG.",
        "",
        "**What this does not measure:** visual fidelity. It is not a WebCGM",
        "conformance certification -- that requires comparing rendered output",
        "against the suite's reference images using the official methodology.",
        "",
        f"Corpus: `{args.corpus.name}`, {len(files)} CGM files.",
        "",
    ]

    for profile in args.profiles:
        per_group, total_time, total_bytes = results[profile]
        tot = collections.Counter()
        for c in per_group.values():
            tot.update(c)
        n = sum(tot.values())
        pct = 100.0 * tot["ok"] / n if n else 0.0
        lines += [
            f"## Profile: `{profile}`",
            "",
            f"**{tot['ok']}/{n} converted ({pct:.1f}%)** in {total_time:.1f}s "
            f"({total_bytes / 1_048_576:.1f} MB of SVG).",
            "",
            "| Group | " + " | ".join(statuses) + " |",
            "| --- | " + " | ".join("---" for _ in statuses) + " |",
        ]
        for group in sorted(per_group):
            c = per_group[group]
            lines.append(f"| `{group}` | " +
                         " | ".join(str(c[s]) for s in statuses) + " |")
        lines += ["", f"| **total** | " +
                  " | ".join(str(tot[s]) for s in statuses) + " |", ""]

    if len(args.profiles) > 1:
        n = len(files)
        same = sum(1 for d in digests.values()
                   if len({d.get(p) for p in args.profiles}) == 1)
        lines += [
            "## Profile divergence",
            "",
            "How often the profiles actually produce different SVG for the same",
            "input, ignoring the generator comment. A profile that never diverged",
            "would not be worth having.",
            "",
            f"Identical across all {len(args.profiles)} profiles: "
            f"**{same}/{n}** ({100.0 * same / n:.1f}%).",
            "",
            "| Profile pair | Files differing | Share |",
            "| --- | --- | --- |",
        ]
        for a, b in itertools.combinations(args.profiles, 2):
            diff = sum(1 for d in digests.values() if d.get(a) != d.get(b))
            lines.append(f"| `{a}` vs `{b}` | {diff} | {100.0 * diff / n:.1f}% |")
        lines.append("")

    if failures:
        lines += ["## Failures", "",
                  "| Profile | File | Status | Detail |",
                  "| --- | --- | --- | --- |"]
        for profile, name, status, detail in failures[:200]:
            d = detail.replace("|", r"\|")[:120]
            lines.append(f"| {profile} | `{name}` | {status} | {d} |")
        if len(failures) > 200:
            lines.append(f"\n_{len(failures) - 200} further failures omitted._")
        lines.append("")
    else:
        lines += ["## Failures", "", "None.", ""]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
